//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

namespace AlbanianXrm.WebResources.DataModel
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum WebResource_WebResourceType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Data (XML)", 3)]
		Data_XML = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GIF format", 6)]
		GIFformat = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ICO format", 9)]
		ICOformat = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("JPG format", 5)]
		JPGformat = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PNG format", 4)]
		PNGformat = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Script (JScript)", 2)]
		Script_JScript = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Silverlight (XAP)", 7)]
		Silverlight_XAP = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("String (RESX)", 11)]
		String_RESX = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Style Sheet (CSS)", 1)]
		StyleSheet_CSS = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Style Sheet (XSL)", 8)]
		StyleSheet_XSL = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vector format (SVG)", 10)]
		Vectorformat_SVG = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Webpage (HTML)", 0)]
		Webpage_HTML = 1,
	}
}